### ISSUE TITLE
DWI concatenation does not work with `--resume`

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#107]
**Describe the Issue**
Concatenation of DWIs with multiple inputs fails when the `--resume` flag is parsed. Issue occurs because `DWIParser` is unable to overwrite the existing file.
<!--
Under the 'Describe the Issue' heading, summarize the issue, linking other issues if they are relevant. Describe your expected results and what results were produced.

**Comment by TheJaeger** [comment]
Traceback:
```
Traceback (most recent call last):
  File "pydesigner.py", line 230, in <module>
    force=args.force)
  File "/Users/sid/Repos/PyDesigner/designer/preprocessing/util.py", line 440, in cat
    raise Exception('Concatenation to ' + str(ext) + 'failed. '
Exception: Concatenation to .niifailed. Please ensure that your input NifTi files have the same phase encoding directions, and are accompanied by valid .bval, .bvec, and .json. If this is not possible, please provide manually concatenated DWIs or run with single series input.
```
