### ISSUE TITLE
Index 22 out of bounds error

### ISSUE THREAD

**Issue by kaytiii** [m-ama/PyDesigner#59]
Receiving the following error across multiple data sets, subjects, and sequences:

```
Path: /Users/kayti/Desktop/Projects/DESIGNER/KTGFDesignerTest/Data/5001/designer/DIFF_siemens_dir_2_7_AVE1
Name: rsdDIFF_siemens_dir_2_7_AVE1
Full: /Users/kayti/Desktop/Projects/DESIGNER/KTGFDesignerTest/Data/5001/designer/DIFF_siemens_dir_2_7_AVE1/rsdDIFF_siemens_dir_2_7_AVE1.nii
No brain mask supplied
Image preprocessed_dwi.nii loaded successfully
Processing with 16 workers...
IRLLS: Noise Estimation : 100%|█| 329476/329476 [00:14<00:00, 22298.82vox/s]
IRLLS: Outlier Detection: 100%|█| 329476/329476 [01:17<00:00, 4261.73vox/s]
Constrained Tensor Fit  :   0%|           | 0/329476 [00:00<?, ?vox/s]Traceback (most recent call last):
  File "/Users/kayti/Repos/PyDesigner-Develop/designer/pydesigner.py", line 552, in <module>
    img.fit(fit_constraints, reject=outliers, dt_hat=dt_est)
  File "/Users/kayti/Repos/PyDesigner-Develop/designer/fitting/dwipi.py", line 568, in fit
    for i in inputs)
  File "/Users/kayti/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 924, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/kayti/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 754, in dispatch_one_batch
    self._pickle_cache)
  File "/Users/kayti/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 210, in __init__
    self.items = list(iterator_slice)
  File "/Users/kayti/Repos/PyDesigner-Develop/designer/fitting/dwipi.py", line 568, in <genexpr>
    for i in inputs)
IndexError: index 22 is out of bounds for axis 1 with size 22
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/kayti/anaconda3/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/Users/kayti/anaconda3/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Users/kayti/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 197, in _python_exit
    thread.join()
  File "/Users/kayti/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/Users/kayti/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

/Users/kayti/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:198: UserWarning: semaphore_tracker: There appear to be 22 leaked semaphores to clean up at shutdown
  len(cache))

```

**Comment by TheJaeger** [comment]
Pull request #60 does not completely fix the issue. Attempting another fix.

**Comment by TheJaeger** [comment]
Issue appears to be fixed. Closing issue.
