### ISSUE TITLE
IRLLS Outlier Detection gets Singular Matrix error

### ISSUE THREAD

**Issue by jbteves** [m-ama/PyDesigner#72]
When running dataset 5001 with the following command
`designer -o ../des/ --denoise --degibbs --rician --mask DIFF_siemens_dir_2_7_AVE1`
I get the following error:
`numpy.linalg.LinAlgError: Singular matrix`
Full traceback:
```
Traceback (most recent call last):
  File "/home/jbteves/PyDesigner/designer/pydesigner.py", line 635, in <module>
    outliers, dt_est = img.irlls()
  File "/home/jbteves/PyDesigner/designer/fitting/dwipi.py", line 1384, in irlls
    (delayed(outlierHelper)(dwi[:, i], bmat, sigma[i,0], b, b0_pos) for i in inputs))
  File "/home/jbteves/miniconda3/envs/designerdev/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/jbteves/miniconda3/envs/designerdev/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jbteves/miniconda3/envs/designerdev/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/jbteves/miniconda3/envs/designerdev/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/jbteves/miniconda3/envs/designerdev/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
```

**Comment by TheJaeger** [comment]
@jbteves would you happen to know whether this occurred in `IRLLS: Noise Estimation` or `IRLLS: Outlier Detection`?

**Comment by jbteves** [comment]
If it's not in the traceback there's no way for me to know.

**Comment by TheJaeger** [comment]
Ignore me, my answer is right there in traceback.
