### ISSUE TITLE
Cannot force run `--degibbs`

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#78]
I have a manually concatenated DWI with a `.json` file that does not contain Fourier information. I do know, however, that this DWI has full Fourier. Here's the error produced:
```
Traceback (most recent call last):
  File "PyDesigner.py", line 307, in <module>
    if args.degibbs and filetable['dwi'].isPartialFourier():
  File "/Users/sid/Repos/PyDesigner/designer/preprocessing/util.py", line 300, in isPartialFourier
    encoding = self.json['PartialFourier']
KeyError: 'PartialFourier'
```
We need to implement an `--adv` flag for advanced users to bypass checks and force a preprocessing step. This would add another `if` after [L310](https://github.com/m-ama/PyDesigner/blob/b5245f6c6bbf2a40438db6b71c5f0f0a90502add/designer/pydesigner.py#L306-L310).
```
if args.degibbs and args.adv:
    args.degibbs = True
```

**Comment by TheJaeger** [comment]
Fixed by #79. Closing.
